name: Shell Commands
on: [push]

jobs:
  run-shell-commmand:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        # run: echo "Hello World"
        run: eecho "Hello World" # eechoを指定
      - name: multiline script
        run: |
          node -v
          npm -v
